name: Build application

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.event_name != 'merge_group' && !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}  # yamllint disable-line

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: '.'
  python-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          python3 -m pip install flake8
      - name: Run linter
        run: |
          python3 -m flake8 .
  ubuntu-gcc-build-perf-stats:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-14 g++-14 ninja-build libmpich-dev libomp-dev valgrind
          python3 -m pip install -r requirements.txt
      - name: Download installed package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-gcc-install
      - name: Extract installed package
        run: |
          mkdir -p install
          tar -xzvf ubuntu-gcc-install.tar.gz -C install
      - name: Run perf count checker
        run: |
          python3 scripts/run_perf_counter.py --required-tests-number=2
      - name: Run perf tests
        run: |
          source scripts/generate_perf_results.sh
      - name: Archive results
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r perf-stat.zip build/perf_stat_dir
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: perf-stat
          path: perf-stat.zip
