name: Build application

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.event_name != 'merge_group' && !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}  # yamllint disable-line

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: '.'
  python-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          python3 -m pip install flake8
      - name: Run linter
        run: |
          python3 -m flake8 .
  ubuntu-gcc-build:
    needs:
      - clang-format
      - python-lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-14 g++-14 ninja-build libmpich-dev libomp-dev valgrind
          python3 -m pip install -r requirements.txt
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-gcc
          create-symlink: true
          max-size: 1G
      - name: CMake configure
        run: >
          cmake -S . -B build
          -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
          -G Ninja -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=ON -D USE_STL=ON
          -D USE_FUNC_TESTS=ON -D USE_PERF_TESTS=ON
          -D CMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=install
        env:
          CC: gcc-14
          CXX: g++-14
      - name: Archive revert list
        uses: actions/upload-artifact@v4
        with:
          name: revert-list
          path: build/revert-list.txt
      - name: Build project
        run: |
          cmake --build build --parallel
        env:
          CC: gcc-14
          CXX: g++-14
      - name: Install project
        run: |
          cmake --build build --target install
      - name: Archive installed package
        run: |
          tar -czvf ubuntu-gcc-install.tar.gz -C install .
      - name: Upload installed package
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-gcc-install
          path: ubuntu-gcc-install.tar.gz
  ubuntu-gcc-test:
    needs:
      - ubuntu-gcc-build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-14 g++-14 ninja-build libmpich-dev libomp-dev valgrind
          python3 -m pip install -r requirements.txt
      - name: Download installed package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-gcc-install
      - name: Extract installed package
        run: |
          mkdir -p install
          tar -xzvf ubuntu-gcc-install.tar.gz -C install
      - name: Run func tests (MPI, num_proc=1)
        run: python3 scripts/run_tests.py --running-type="processes"
        env:
          PROC_COUNT: 1
          OMP_NUM_THREADS: 3
      - name: Run func tests (MPI, num_proc=2)
        run: python3 scripts/run_tests.py --running-type="processes"
        env:
          PROC_COUNT: 2
          OMP_NUM_THREADS: 2
      - name: Run func tests (MPI, num_proc=3)
        run: python3 scripts/run_tests.py --running-type="processes"
        env:
          PROC_COUNT: 3
          OMP_NUM_THREADS: 1
      - name: Run func tests (MPI, num_proc=4)
        run: python3 scripts/run_tests.py --running-type="processes"
        env:
          PROC_COUNT: 4
          OMP_NUM_THREADS: 1
      - name: Run func tests (threads, num_threads=1)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 1
      - name: Run func tests (threads, num_threads=2)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 2
      - name: Run func tests (threads, num_threads=3)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 3
      - name: Run func tests (threads, num_threads=4)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 4
  ubuntu-gcc-test-extended:
    needs:
      - ubuntu-gcc-test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-14 g++-14 ninja-build libmpich-dev libomp-dev valgrind
          python3 -m pip install -r requirements.txt
      - name: Download installed package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-gcc-install
      - name: Extract installed package
        run: |
          mkdir -p install
          tar -xzvf ubuntu-gcc-install.tar.gz -C install
      - name: Run func tests (threads, num_threads=16)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 16
  ubuntu-clang-build:
    needs:
      - clang-format
      - python-lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ninja-build libmpich-dev python3-pip valgrind
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 19 all
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-clang
          create-symlink: true
          max-size: 1G
      - name: CMake configure
        run: >
          cmake -S . -B build
          -G Ninja -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=ON -D USE_STL=ON
          -D USE_FUNC_TESTS=ON -D USE_PERF_TESTS=ON
          -D CMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=install
        env:
          CC: clang-19
          CXX: clang++-19
      - name: Build project
        run: |
          cmake --build build --parallel
        env:
          CC: clang-19
          CXX: clang++-19
      - name: Install project
        run: |
          cmake --build build --target install
      - name: Archive installed package
        run: |
          tar -czvf ubuntu-clang-install.tar.gz -C install .
      - name: Upload installed package
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-clang-install
          path: ubuntu-clang-install.tar.gz
  ubuntu-clang-test:
    needs:
      - ubuntu-clang-build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ninja-build libmpich-dev python3-pip valgrind
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 19 all
      - name: Download installed package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-clang-install
      - name: Extract installed package
        run: |
          mkdir -p install
          tar -xzvf ubuntu-clang-install.tar.gz -C install
      - name: Run func tests (MPI, num_proc=1)
        run: python3 scripts/run_tests.py --running-type="processes"
        env:
          PROC_COUNT: 1
          OMP_NUM_THREADS: 3
      - name: Run func tests (MPI, num_proc=2)
        run: python3 scripts/run_tests.py --running-type="processes"
        env:
          PROC_COUNT: 2
          OMP_NUM_THREADS: 2
      - name: Run func tests (MPI, num_proc=3)
        run: python3 scripts/run_tests.py --running-type="processes"
        env:
          PROC_COUNT: 3
          OMP_NUM_THREADS: 1
      - name: Run func tests (MPI, num_proc=4)
        run: python3 scripts/run_tests.py --running-type="processes"
        env:
          PROC_COUNT: 4
          OMP_NUM_THREADS: 1
      - name: Run tests (threads, num_threads=1)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 1
      - name: Run tests (threads, num_threads=2)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 2
      - name: Run tests (threads, num_threads=3)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 3
      - name: Run tests (threads, num_threads=4)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 4
  ubuntu-clang-test-extended:
    needs:
      - ubuntu-clang-test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ninja-build libmpich-dev python3-pip valgrind
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 19 all
      - name: Download installed package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-clang-install
      - name: Extract installed package
        run: |
          mkdir -p install
          tar -xzvf ubuntu-clang-install.tar.gz -C install
      - name: Run tests (threads, num_threads=8)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 8
      - name: Run tests (threads, num_threads=16)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 16
  ubuntu-clang-sanitizer-build:
    needs:
      - ubuntu-clang-build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ninja-build libmpich-dev mpi* openmpi-bin python3-pip
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 19 all
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-clang
          create-symlink: true
          max-size: 1G
      - name: CMake configure
        run: >
          cmake -S . -B build
          -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
          -G Ninja -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=ON -D USE_STL=ON
          -D USE_FUNC_TESTS=ON -D USE_PERF_TESTS=ON
          -D CMAKE_BUILD_TYPE=RELEASE -D ENABLE_ADDRESS_SANITIZER=ON -D ENABLE_UB_SANITIZER=ON
          -DCMAKE_INSTALL_PREFIX=install
        env:
          CC: clang-19
          CXX: clang++-19
      - name: Build project
        run: |
          cmake --build build --parallel
        env:
          CC: clang-19
          CXX: clang++-19
      - name: Install project
        run: |
          cmake --build build --target install
      - name: Archive installed package
        run: |
          tar -czvf ubuntu-clang-sanitizer-install.tar.gz -C install .
      - name: Upload installed package
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-clang-sanitizer-install
          path: ubuntu-clang-sanitizer-install.tar.gz
  ubuntu-clang-sanitizer-test:
    needs:
      - ubuntu-clang-sanitizer-build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ninja-build libmpich-dev python3-pip valgrind
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 19 all
      - name: Download installed package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-clang-sanitizer-install
      - name: Extract installed package
        run: |
          mkdir -p install
          tar -xzvf ubuntu-clang-sanitizer-install.tar.gz -C install
      - name: Run tests (MPI)
        run: python3 scripts/run_tests.py --running-type="processes" --additional-mpi-args="--oversubscribe"
        env:
          PROC_COUNT: 2
          OMP_NUM_THREADS: 2
          ASAN_RUN: 1
          ASAN_OPTIONS: abort_on_error=1
          UBSAN_OPTIONS: halt_on_error=1
      - name: Run tests (threads, num_threads=1)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 1
          ASAN_RUN: 1
          ASAN_OPTIONS: abort_on_error=1
          UBSAN_OPTIONS: halt_on_error=1
      - name: Run tests (threads, num_threads=2)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 2
          ASAN_RUN: 1
          ASAN_OPTIONS: abort_on_error=1
          UBSAN_OPTIONS: halt_on_error=1
      - name: Run tests (threads, num_threads=3)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 3
          ASAN_RUN: 1
          ASAN_OPTIONS: abort_on_error=1
          UBSAN_OPTIONS: halt_on_error=1
      - name: Run tests (threads, num_threads=4)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 4
          ASAN_RUN: 1
          ASAN_OPTIONS: abort_on_error=1
          UBSAN_OPTIONS: halt_on_error=1
  ubuntu-clang-sanitizer-test-extended:
    needs:
      - ubuntu-clang-sanitizer-test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ninja-build libmpich-dev python3-pip valgrind
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 19 all
      - name: Download installed package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-clang-sanitizer-install
      - name: Extract installed package
        run: |
          mkdir -p install
          tar -xzvf ubuntu-clang-sanitizer-install.tar.gz -C install
      - name: Run tests (threads, num_threads=5)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 5
          ASAN_RUN: 1
      - name: Run tests (threads, num_threads=6)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 6
          ASAN_RUN: 1
      - name: Run tests (threads, num_threads=7)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 7
          ASAN_RUN: 1
      - name: Run tests (threads, num_threads=8)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 8
          ASAN_RUN: 1
      - name: Run tests (threads, num_threads=11)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 11
          ASAN_RUN: 1
      - name: Run tests (threads, num_threads=13)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 13
          ASAN_RUN: 1
      - name: Run tests (threads, num_threads=15)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 15
          ASAN_RUN: 1
      - name: Run tests (threads, num_threads=16)
        run: python3 scripts/run_tests.py --running-type="threads"
        env:
          OMP_NUM_THREADS: 16
          ASAN_RUN: 1
  ubuntu-gcc-build-perf-stats:
    needs:
      - ubuntu-gcc-build-codecov
      - ubuntu-clang-sanitizer-test-extended
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-14 g++-14 ninja-build libmpich-dev libomp-dev valgrind
          python3 -m pip install -r requirements.txt
      - name: Download installed package
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-gcc-install
      - name: Extract installed package
        run: |
          mkdir -p install
          tar -xzvf ubuntu-gcc-install.tar.gz -C install
      - name: Run perf count checker
        run: |
          python3 scripts/run_perf_counter.py --required-tests-number=2
      - name: Run perf tests
        run: |
          source scripts/generate_perf_results.sh
      - name: Archive results
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r perf-stat.zip build/perf_stat_dir
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: perf-stat
          path: perf-stat.zip
